// <auto-generated />
namespace HYY.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class fixedidonappointment : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(fixedidonappointment));
        
        string IMigrationMetadata.Id
        {
            get { return "202009030105295_fixed id on appointment"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
